### Get CSRF Token
GET http://localhost:3000/api/v1/auth/csrf-token

### Signup
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json
X-CSRF-Token: {{csrfToken}}

{
    "firstName": "Abdullah",
    "lastName": "Odulate",
    "userName": "abdullahodulate",
    "email": "abdulluhodulate@gmail.com",
    "password": "password123"
}

### Verify Email
POST http://localhost:3000/api/v1/auth/verify-email
Content-Type: application/json
X-CSRF-Token: {{csrfToken}}

{
    "email": "abdulluhodulate@gmail.com",
    "otp": "123456"
}

### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json
X-CSRF-Token: {{csrfToken}}

{
    "email": "abdulluhodulate@gmail.com",
    "password": "password123"
}

@csrfToken = ZGm9TuuU-T9pQAeBV8W4gfP4D3G0hYxR8U8w